apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jeremiahbuckley-t2-poi-map-app-dev
  annotations:
    argocd/app-name: jeremiahbuckley-t2-poi-map-app-dev
    backstage.io/kubernetes-id: jeremiahbuckley-t2-poi-map-app
    backstage.io/kubernetes-namespace: jeremiahbuckley-t2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/jeremiahbuckley-t2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/jeremiahbuckley-t2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/jeremiahbuckley-t2/deployments/jeremiahbuckley-t2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/jeremiahbuckley-t2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jeremiahbuckley-t2-poi-map-app-jeremiahbuckley-t2.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jeremiahbuckley"
  system: workshop-system-jeremiahbuckley-t2
  consumesApis:
    - gateway-api-jeremiahbuckley-t2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jeremiahbuckley-t2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jeremiahbuckley"
